image: "docker:latest"

stages:
  - test
  - build
  - image
  - push

test:
  stage: test
  script:
    - echo "TEST EXECUTION STARTED"
    - make test

build:
  stage: build
  script:
    - echo "BUILD EXECUTION STARTED"
    - make build


push:
  stage: push
  script:
    - echo "PUSH EXECUTION STARTED"
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - make push
