variables:
  REPO: "https://github.com/cipgen/kbot"
  BRANCH: "main"

stages:
  - clone
  - test
  - build
  - image
  - push

clone_repository:
  stage: clone
  script:
    - echo 'CLONE REPOSITORY'
    - git clone -b $BRANCH $REPO

test_execution:
  stage: test
  script:
    - echo 'TEST EXECUTION STARTED'
    - make test

build_execution:
  stage: build
  script:
    - echo 'BUILD EXECUTION STARTED'
    - make build

image_execution:
  stage: image
  script:
    - echo 'IMAGE EXECUTION STARTED'
    - make image

push_execution:
  stage: push
  script:
    - echo 'PUSH EXECUTION STARTED'
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
    - make push
