image: golang:1.21

variables:
  REPO: "https://github.com/cipgen/kbot"
  BRANCH: "main"
  REGISTRY: "registry.gitlab.com/cipgen"
  OS: "linux"
  ARCH: "amd64"
  VER: "v1.0.9"
  APP: "kbot"

  SUPPORT_IMAGE: "docker:19.03.12"
  SUPPORT_SERVICE: "docker:19.03.12-dind" 


stages:
  - clone
  - test
  - build
  - image
  - push

clone_repository:
  stage: clone
  script:
    - echo 'CLONE REPOSITORY'
    - rm -rf kbot || true  # This will ignore errors if the directory doesn't exist
    - git clone -b $BRANCH $REPO

test_execution:
  stage: test
  script:
    - echo 'TEST EXECUTION STARTED'
    - make test

build_execution:
  stage: build
  before_script:
    - export SHORTVERS=$(git rev-parse --short HEAD)
    - echo "Short version is $SHORTVERS"
  script:
    - VERSION="${VER}-${SHORTVERS}"
    - echo "Full version is $VERSION"
    - echo 'BUILD EXECUTION STARTED'
    - make build TARGETOS=$OS TARGETARCH=$ARCH VERSION=$VERSION
  

image_execution:
  stage: image
  image: $SUPPORT_IMAGE
  services:
    - name: $SUPPORT_SERVICE
      alias: docker
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - docker build . -t ${CI_REGISTRY_IMAGE}:TARGETOS=$OS TARGETARCH=$ARCH VERSION=$VERSION
    - docker push ${CI_REGISTRY_IMAGE}:TARGETOS=$OS TARGETARCH=$ARCH VERSION=$VERSION
    - docker logout
