image: golang:1.20

stages:
  - format
  - lint
  - test
  - build
  - build_image
  - push
  - clean

format:
  stage: format
  script:
    - make format

lint:
  stage: lint
  script:
    - make lint

test:
  stage: test
  script:
    - make test

build:
  stage: build
  script:
    - make build

build_image:
  stage: build_image
  script:
    - make image

push:
  stage: push
  script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - make push

clean:
  stage: clean
  script:
    - make clean
