image: golang:1.21

variables:
  REPO: "https://github.com/cipgen/kbot"
  BRANCH: "main"
  REGISTRY: "registry.gitlab.com/cipgen"
  APP: "kbot"
  GHCR: "https://registry.gitlab.com"
  USER_NAME: cipgen
  

stages:
  - clone
  - test
  - build
  - image_
  - push

clone:
  stage: clone
  script:
    - echo 'ClONE REPOSITORY'
    - |
      if [ -d $APP ]; then
        rm -r $APP
        echo "Folder removed"
      else
        echo "Folder dosn't exists"
      fi
    - git clone -b ${BRANCH} ${REPO}

cache:
  paths:
  - kbot/
  
test:
  stage: test
  script:
    - echo 'TEST STARTED'
    - cd $APP
    - make test
  dependencies:
    - clone

build:
  stage: build
  dependencies:
    - test
  script:
    - echo 'BUILD STARTED'
    - cd $APP
    - make build TARGETOS=$OS TARGETARCH=$ARCH

image_:
  stage: image_
  dependencies:
    - build
  script:
    - echo 'IMAGE STARTED'
    - cd $APP
    - make image REGISTRY=$REGISTRY APP=$APP TARGETOS=$OS TARGETARCH=$ARCH
