image: golang:1.20

stages:
  - format
  - lint
  - test
  - build
  - build_image
  - push
  - clean

before_script:
  - go install golang.org/x/lint/golint@latest

format:
  stage: format
  script:
    - make format

lint:
  stage: lint
  script:
    - make lint

test:
  stage: test
  script:
    - make test

build:
  stage: build
  script:
    - make build

build_image:
  stage: build_image
  script:
    - echo "Building Docker Image"
    - docker build -t cipgen/kbot:$CI_COMMIT_SHORT_SHA .
    - docker push cipgen/kbot:$CI_COMMIT_SHORT_SHA

push:
  stage: push
  script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - make push

clean:
  stage: clean
  script:
    - make clean
