image: golang:1.21


variables:
  REPO: "https://github.com/cipgen/kbot"
  BRANCH: "main"
  REGISTRY: "registry.gitlab.com/cipgen"
  VERSION: v1.0.9
  APP: "kbot"
  SUPPORT_SERVICE: "docker:24.0.7-dind" 

  TARGETOS: linux
  TARGETARCH: amd64
  BUILDS_DIR: out


stages:
  - clone
  - test
  - build
  - makeimage
  - push

clone_repository:
  stage: clone
  script:
    - echo 'CLONE REPOSITORY'
    - rm -rf kbot || true  
    - git clone -b $BRANCH $REPO

test_execution:
  stage: test
  script:
    - echo 'TEST EXECUTION STARTED'
    - make test

build_execution:
  stage: build
  before_script:
    - export SHORTC=$(git rev-parse --short HEAD)
    - echo "Short commit is $SHORTC"

  script:
    - gofmt -s -w ./
    - go get
    - CGO_ENABLED=0 GOOS=${TARGETOS} GOARCH=${TARGETARCH} go build -v -o ./${BUILDS_DIR}/$APP -ldflags "-X=${BUILD_URL}/cmd.appVersion=$VERSION-$SHORTC"

image_build_execution:
  stage: makeimage
  dependencies:
    - build
  script:
    - echo 'IMAGE STARTED'
    - cd $APP
    - make image REGISTRY=${CI_REGISTRY_IMAGE} APP=$APP TARGETOS=$OS TARGETARCH=$ARCH

push_execution:
  stage: push
  image: docker:latest
  services:
    - name: $SUPPORT_SERVICE
      alias: docker
  variables:
    IMAGE_TAG: ${CI_REGISTRY_IMAGE}:${VERSION}-${TARGETOS}-${TARGETARCH}
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - docker build . -t $IMAGE_TAG --build-arg TARGETOS=${TARGETOS} --build-arg TARGETARCH=${TARGETARCH}
    - docker push $IMAGE_TAG
    - docker logout
