image: golang:1.21


variables:
  REPO: "https://github.com/cipgen/kbot"
  BRANCH: "main"
  REGISTRY: "registry.gitlab.com/cipgen"
  VERSION: v1.0.9
  APP: "kbot"


stages:
  - clone
  - test
  - build
  - makeimage
  - push

clone_repository:
  stage: clone
  script:
    - echo 'CLONE REPOSITORY'
    - rm -rf kbot || true  
    - git clone -b $BRANCH $REPO

test_execution:
  stage: test
  script:
    - echo 'TEST EXECUTION STARTED'
    - make test

build_execution:
  stage: build
  before_script:
    - export SHORTC=$(git rev-parse --short HEAD)
    - echo "Short commit is $SHORTC"

  script:
    - gofmt -s -w ./
    - go get
    - CGO_ENABLED=0 GOOS=${TARGETOS} GOARCH=${TARGETARCH} go build -v -o ./${BUILDS_DIR}/$APP -ldflags "-X=${BUILD_URL}/cmd.appVersion=$VERSION-$SHORTC"


image_:
  stage: makeimage
  dependencies:
    - build
  script:
    - echo 'IMAGE STARTED'
    - cd $APP
    - make image REGISTRY=$REGISTRY APP=$APP TARGETOS=$OS TARGETARCH=$ARCH
