image: golang:1.21

variables:
  REPO: "https://github.com/cipgen/mod6_task3"
  BRANCH: "main"
  REGISTRY: "registry.gitlab.com/cipgen"
  OS: "linux"
  ARCH: "amd64"
  VER: "v1.0.10"
  APP: "kbot"

  TARGETOS: linux
  TARGETARCH: amd64

stages:
  - clone
  - test
  - build
  - image
  - push

clone_repository:
  stage: clone
  script:
    - echo 'CLONE REPOSITORY'
    - rm -rf kbot || true  # This will ignore errors if the directory doesn't exist
    - git clone -b $BRANCH $REPO

test_execution:
  stage: test
  script:
    - echo 'TEST EXECUTION STARTED'
    - make test

build_execution:
  stage: build
  before_script:
    - export SHORTVERS=$(git rev-parse --short HEAD)
    - echo "Short version is $SHORTVERS"
  script:
    - VERSION="${VER}-${SHORTVERS}"
    - echo "Full version is $VERSION"
    - echo 'BUILD EXECUTION STARTED'
    - make build TARGETOS=$OS TARGETARCH=$ARCH VERSION=$VERSION
  

image_execution:
  stage: image docker:24.0.7
  services:
    - docker:24.0.7-dind
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - echo "Building image with tag ${CI_REGISTRY_IMAGE}:${VER}-${OS}-${ARCH}"
    - docker build . -t ${CI_REGISTRY_IMAGE}:${VER}-${OS}-${ARCH} --build-arg TARGETOS=${TARGETOS} --build-arg TARGETARCH=${TARGETARCH}
    - echo "Pushing image ${CI_REGISTRY_IMAGE}:${VER}-${OS}-${ARCH}"
    - docker push ${CI_REGISTRY_IMAGE}:${VER}-${OS}-${ARCH}
    - docker logout

