image: golang:1.21

variables:
  SUPPORT_IMAGE: "docker:latest"
  SUPPORT_SERVICE: "docker:dind"
  GIT_STRATEGY: clone
  VER: v1.0.9
  GIT_DEPTH: 1

  TARGETOS: linux
  TARGETARCH: amd64
  BUILDS_DIR: out


stages:
  - create_vars
  - info        
  - test
  - build
  - image

vars-job:
  stage: create_vars  
  script:
    - echo "VERSION=$(git describe --tags --abbrev=0)-$(git rev-parse --short HEAD)" >> build.env
    - echo "BUILD_URL=github.com/cipgen/kbot" >> build.env
  artifacts:
    reports:
      dotenv: build.env
    
test-job:
  stage: test    
  script:
    - go test -v

build-job:
  stage: build
  script:
    - gofmt -s -w ./
    - go get
    - CGO_ENABLED=0 GOOS=${TARGETOS} GOARCH=${TARGETARCH} go build -v -o ./${BUILDS_DIR}/kbot -ldflags "-X=${BUILD_URL}/cmd.appVersion=${VERSION}"


image-job:
  stage: image
  image: $SUPPORT_IMAGE
  services:
    - name: $SUPPORT_SERVICE
      alias: docker
  variables:
    IMAGE_TAG: ${CI_REGISTRY_IMAGE}:${VER}-${TARGETOS}-${TARGETARCH}
  script:
    - docker build . -t $IMAGE_TAG --build-arg TARGETOS=${TARGETOS} --build-arg TARGETARCH=${TARGETARCH}
  artifacts:
    paths:
      - $IMAGE_TAG
    expire_in: 1 hour

# Job for pushing the Docker image
push-job:
  stage: push
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - docker push $IMAGE_TAG
    - docker logout
  needs:
    - image-job