image: golang:1.21


variables:
  REPO: "https://github.com/cipgen/kbot"
  BRANCH: "main"
  REGISTRY: "registry.gitlab.com/cipgen"



stages:
  - clone
  - test
  - build
  - image
  - push

clone_repository:
  stage: clone
  script:
    - echo 'CLONE REPOSITORY'
    - rm -rf kbot || true  # This will ignore errors if the directory doesn't exist
    - git clone -b $BRANCH $REPO

test_execution:
  stage: test
  script:
    - echo 'TEST EXECUTION STARTED'
    - make test

build_execution:
  stage: build
  script:
    - echo 'BUILD EXECUTION STARTED'
    - make build TARGETOS=$OS TARGETARCH=$ARCH
