stages:
  - test
  - build
  - dockerize

variables:
  REGISTRY: git@gitlab.com:cipgen/kbot.git
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA

before_script:
  - echo "Starting CI/CD Pipeline for the project"

test:
  stage: test
  script:
    - echo "Running tests"
    - make test

build:
  stage: build
  script:
    - echo "Building the project"
    - make build

dockerize:
  stage: dockerize
  script:
    - echo "Building Docker Image using original Dockerfile"
    - make image
    - echo "Pushing Docker Image to registry"
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $REGISTRY
    - make push
  only:
    - main
